; PlatformIO 项目配置文件
;
;   编译选项：编译参数、源码过滤规则
;   上传选项：自定义串口、上传波特率、额外指令参数
;   库管理选项：项目依赖库、额外库存放目录
;   高级功能选项：自定义编译/上传脚本
;
; 如需查看全部配置选项与示例，请访问官方文档
; https://docs.platformio.org/page/projectconf.html

; 【旧错误环境：普通ESP32双核，不兼容ESP32-C3，已注释禁用】
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

; 【适配WeAct/Waveshare ESP32-C3 Zero 专用环境】
[env:esp32c3]
# 乐鑫ESP32系列硬件平台
platform = espressif32
# WeAct ESP32C3 Core / C3 Zero 官方识别ID
board = weactstudio_esp32c3coreboard
# 使用Arduino开发框架
framework = arduino
# Flash大小：芯片实际4MB
board_build.flash_size = 4MB
# 自定义分区表：双APP槽位各1.25MB，支持OTA远程升级，SPIFFS约1.375MB
board_build.partitions = partitions.csv
# 上传波特率
upload_speed = 921600
# 串口监视器波特率
monitor_speed = 115200
# 编译优化
build_flags =
    -Os
    -DCORE_DEBUG_LEVEL=2
# 文件系统：SPIFFS（网页静态资源存储）
board_build.filesystem = spiffs
# 库依赖
lib_deps =
    knolleary/PubSubClient@^2.8
    fastled/FastLED@^3.7
